chain_id = "test-cosmos"
validators = 2
accounts = 21
binary = "wasmd"
hrp_prefix = "wasm"
denom = "stake"
coin_type = 118

[config_node.app]
minimum-gas-prices = "0.10stake"
api = { enable = true, swagger = true, enabled-unsafe-cors = true }
rosetta = { enable = false }

[config_node.config]
instrumentation = { prometheus = false }
p2p = { addr_book_strict = false, allow_duplicate_ip = true }

[config_genesis.app_state.gov]
voting_params = { voting_period = "600s" }

[config_genesis.app_state.mint]
minter = { inflation = "0.300000000000000000" }
